[pytest]
addopts = -v -s --alluredir=reports --maxfail=1
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    slow: тесты, которые выполняются долго